spring.application.name=ai-code-explainer

server.port = 8080

#AI related things below-----

gemini.api.key=AIzaSyDv3x2SQ0SaSrCE84tRvXCwQ0uDusAkOgk

gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent